449: Hero spacing issues
urfuwo/hlx-test pull request #450
Opened 2024-04-07 19:17 UTC by rjwtrmn

- Hero background should be continuous with background of following section (i.e. no white margin between sections with colourful backgrounds)
- Spacing between hero content elements should now more closely match the Figma designs.
- Hero text content width should take up more of the space at larger screen sizes as per Figma.
- Vertical hero padding should adjust according to breakpoints (40px -> 48px -> 56px);

Fix #449

Test URLs:
Design Page with hero margin issue
- Before: https://main--hlx-test--urfuwo.hlx.live/design/stories-resources
- After: https://449-hero-bottom-margin--hlx-test--urfuwo.hlx.live/design/stories-resources

L3
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/ext-how-ai-powered-cybersecurity-combats-ai-threats
- After: https://449-hero-bottom-margin--hlx-test--urfuwo.hlx.live/blog/ext-how-ai-powered-cybersecurity-combats-ai-threats

L2
- Before: https://main--hlx-test--urfuwo.hlx.live/topics/sustainability
- After: https://449-hero-bottom-margin--hlx-test--urfuwo.hlx.live/topics/sustainability

L1
- Before: https://main--hlx-test--urfuwo.hlx.live/topics
- After: https://449-hero-bottom-margin--hlx-test--urfuwo.hlx.live/topics

2024-04-08 04:45 UTC, benpeter approved these changes

2024-04-08 09:08 UTC, saurabh-khare approved these changes

2024-04-08 09:17 UTC, saurabh-khare requested changes
Sorry, please check why the score dropped for /design/stories-resources
Is a CLS detected? Also is this caused by this PR?

2024-04-12 09:00 UTC, saurabh-khare approved these changes

2024-04-12 10:27 UTC, merged